services:
  api:
    build: ./tp-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./tp-api/data:/app/data
  client:
    build: ./tp-client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
    volumes:
      - ./tp-client:/app
      - client_node_modules:/app/node_modules
    command: npm run dev
volumes:
  client_node_modules:
